Repository DevelopLife/reviewtwits_frontend, pull requests merged in 2023-04, with the labels that each got.

#111 [FEATURE] 소셜 리뷰 작성 구현
  api/sns.ts
  components/review/common/ImageUploadBox.tsx
  components/social/review/ReviewWriteForm.tsx
  components/social/review/SearchBar.tsx
  constants/reviews.ts
  hooks/useForm.tsx
  typings/reviews.ts
  utils/regExp.ts
  utils/validate.ts
Labels: feature

#113 [FEATURE] 401 or 403 에러인 경우 로그인 페이지로 일괄 리다이렉트
  api/instance.ts
  components/Project/Management/ProjectManagementSection.tsx
  pages/project/plans/index.tsx
  utils/errorHandler.ts
  utils/windowNavigate.ts
Labels: feature

#126 [FEATURE] social follow and unfollow를 처리하는 hook 생성
  api/instance.ts
  api/sns.ts
  hooks/useFollowAndUnFollow.tsx
  typings/error.ts
  utils/errorHandler.ts
Labels: feature

#123 [FEATURE] feed Review를 누르면 모달 생성
  components/common/Modal/ModalContainer.tsx
  components/common/Modal/SocialFeedModal/AddCommentForm.tsx
  components/common/Modal/SocialFeedModal/Comment.tsx
  components/common/Modal/SocialFeedModal/Comments.tsx
  components/common/Modal/SocialFeedModal/Contants.tsx
  components/common/Modal/SocialFeedModal/DetailImage.tsx
  components/common/Modal/SocialFeedModal/Reactions.tsx
  components/common/Modal/SocialFeedModal/Reviewer.tsx
  components/common/Modal/SocialFeedModal/index.tsx
  components/common/Modal/modals.ts
  components/sns/common/SocialCard.styles.ts
  components/social/feed/MainContentSection/Review.tsx
  constants/modal.ts
  hooks/useModal.tsx
  pages/_app.tsx
  states/AtomModal.ts
  styles/theme.ts
Labels: feature

#124 [FEATURE] 소셜 마이프로필 페이지 API 연동
  api/sns.ts
  components/social/profile/EditProfileButton.tsx
  components/social/profile/SocialFeedSection.tsx
  components/social/profile/SocialFollowButton.test.tsx
  components/social/profile/SocialFollowButton.tsx
  components/social/profile/SocialProfileCard.tsx
  components/social/profile/SocialProfileImage.tsx
  components/social/profile/SocialUnFollowButton.test.tsx
  components/social/profile/SocialUnFollowButton.tsx
  constants/followAndUnFollow.ts
  constants/mockSocialProfile.ts
  hooks/useGetSocialProfile.tsx
  hooks/useGetSocialReviews.tsx
  jest.config.js
  pages/social/profile/index.tsx
  typings/social.ts
Labels: feature

#129 [FEATURE] sns follower / following 리스트를 받아오는 api로직 작성
  api/sns.ts
  hooks/queries/sns.ts
  typings/sns.ts
Labels: feature

#134 [FIX] Next.js Image 최적화시 naverlogin_sdk 에러 해결
  components/common/Oauth/NaverOauth.tsx
Labels: bug

#137 [ADD] 프론트 반복작업 코드 Code Snippets 적용
  .vscode/settings.json
  .vscode/typescript.code-snippets
Labels: documentation, Suggest

#142 [FEATURE] shoppingmall review api 연결
  api/reviews.ts
  components/ShoppingMallReview/ComprehensiveRates.styles.ts
  components/ShoppingMallReview/ComprehensiveRates.tsx
  components/ShoppingMallReview/Review.styles.ts
  components/ShoppingMallReview/Review.tsx
  components/ShoppingMallReview/Reviews.tsx
  components/ShoppingMallReview/ShoppingMallReview.tsx
  hooks/queries/reviews.ts
  hooks/queries/sns.ts
  pages/shoppingMallReview.tsx
  typings/reviews.ts
  utils/format.ts
Labels: feature

#140 [FEATURE] infinitescroll 기능을 위한 로직 구현
  api/sns.ts
  components/social/feed/MainContentSection/index.tsx
  hooks/queries/sns.ts
  hooks/queries/useInfiniteScrollQuery.tsx
  hooks/useIntersectionObserver.tsx
  utils/linkageDataToArray.ts
Labels: feature

#178 [FEATURE] social home feed page에 infiniteScroll 적용
  components/social/feed/MainContentSection/index.tsx
  hooks/queries/sns.ts
Labels: feature
